name: Generate Python Client

on:
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Python Client
        uses: openapi-generators/openapi-python-client-action@v2
        with:
          openapi-url: "https://raw.githubusercontent.com/formkiq/formkiq-core/refs/heads/master/docs/openapi/openapi-jwt.yaml"
          config-file: "./client-config.yaml"
          args: "--output-path formkiq-client"

      - name: Show output (debug)
        run: |
          ls -la
          ls -la formkiq-client || true

      - name: Install and test
        run: |
          python3 -m pip install -U pip
          pip install -e formkiq-client
          # The importable package is "formkiq_client"
          pytest --maxfail=1 --disable-warnings -q